### ISSUE TITLE
Compilation error after disable MQTT in settings.h 

### ISSUE THREAD

**Issue by JureqB** [Resinchem/3D-LED-Clock#3]
...  Documents\Arduino\3D-LED-Clock-1.00\clock_main\clock_main.ino: In function 'boolean reconnect()':
clock_main:95:37: error: 'mqttUser' was not declared in this scope
   95 |   if (client.connect("ClockClient", mqttUser, mqttPW)) {
      |                                     ^~~~~~~~
clock_main:95:47: error: 'mqttPW' was not declared in this scope
   95 |   if (client.connect("ClockClient", mqttUser, mqttPW)) {
      |                                               ^~~~~~
exit status 1
'mqttUser' was not declared in this scope

**Comment by Resinchem** [comment]
There were some missing checks for the MQTT enabled status.  These have been fixed with release v1.01.  Please see the [release notes](https://github.com/Resinchem/3D-LED-Clock/releases/tag/v1.01) for more info.
